server:
  port: 8085
spring:
profiles:
  active: ${ACTIVE_SPRING_PROFILE:local}

gitapi:
  base-url:  ${GIT_REPO_BASE_URL:https://api.github.com/}
  path: search/repositories

springdoc:
  default-produces-media-type: application/json
  show-actuator: true
  override-with-generic-response: false
  pathsToMatch:
    - /v1/**
  swagger-ui.path: /v3/swagger-ui.html

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web.exposure.include: info, health, metrics, prometheus