apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: git-repositories-svc
  labels:
    run: git-repositories-svc
spec:
  type: NodePort # type of the service.
  selector:
    app: git-repositories
  ports:
    - protocol: "TCP"
      port: 8085 # The port that the service is running on in the cluster
      targetPort: 8085 # The port exposed by the service
